api:
  image: todos-back
  ports:
    - 8080:80
  links:
    - database:database
tester:
  image: todos-back:dev
  links:
    - api:api
    - database:database
database:
  image: mariadb:5.5
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: default
